[Variables]

; Theme
;   light or dark
Theme=dark

; Units of Measurement
;   https://openweathermap.org/current#data
Units=metric

; Language
;   https://openweathermap.org/current#multi
;   WARNING: Only English has been tested. Other languages may require
;            modification of the regex string at Weather.ini:108 if parse
;            errors are encountered.
Lang=en

; Location
;   https://openweathermap.org/current#geo
Lat=
Long=

; API Key
;   https://home.openweathermap.org/api_keys
Key=
